version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: go_internist_db
    environment:
      POSTGRES_DB: go_internist
      POSTGRES_USER: internist
      POSTGRES_PASSWORD: medical_ai_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
