# File: docker-compose.yml
services:
  app:
    container_name: go_internist_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development # Use this instead of APP_ENV to match your config.go
      - DB_HOST=postgres
      - DB_USER=internist
      - DB_PASSWORD=medical_ai_2025
      - DB_NAME=go_internist
      - DB_PORT=5432 
      # Add ALL other required variables from your .env file here
      - JWT_SECRET_KEY=A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0
      - AVALAI_API_KEY_EMBEDDING=${AVALAI_API_KEY_EMBEDDING}
      - AVALAI_API_KEY_TRANSLATION=${AVALAI_API_KEY_TRANSLATION}
      - JABIR_API_KEY=${JABIR_API_KEY}
      # 🔄 UPDATED: Qdrant variables (replacing Pinecone)
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - SMS_ACCESS_KEY=${SMS_ACCESS_KEY}
      - SMS_API_URL=${SMS_API_URL}
      - SMS_TEMPLATE_ID=512130
      - ADMIN_PHONE_NUMBER=09371997640
      # Additional variables from your .env
      - RAG_TOPK=8
      - TRANSLATION_ENABLED=true
      - EMBEDDING_MODEL_NAME=text-embedding-3-large
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: go_internist_db
    environment:
      - POSTGRES_DB=go_internist
      - POSTGRES_USER=internist
      - POSTGRES_PASSWORD=medical_ai_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"     # <-- changed host port to 15432 to resolve port conflict
    restart: unless-stopped

volumes:
  postgres_data:
